# Quick Stripe Setup Script for JARVIS Omega
# This script helps you get started with Stripe quickly

Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║      JARVIS OMEGA - Stripe Quick Setup Guide              ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

Write-Host "STEP 1: Create Stripe Account" -ForegroundColor Yellow
Write-Host "  → Go to: https://stripe.com" -ForegroundColor White
Write-Host "  → Sign up for a free account (takes 2 minutes)" -ForegroundColor White
Write-Host ""

$response = Read-Host "Have you created your Stripe account? (y/n)"
if ($response -ne 'y') {
    Write-Host "Please create your Stripe account first, then run this script again." -ForegroundColor Red
    exit 0
}

Write-Host ""
Write-Host "STEP 2: Get API Keys" -ForegroundColor Yellow
Write-Host "  → Go to: https://dashboard.stripe.com/test/apikeys" -ForegroundColor White
Write-Host "  → Copy your 'Publishable key' (starts with pk_test_)" -ForegroundColor White
Write-Host "  → Click 'Reveal test key' and copy 'Secret key' (starts with sk_test_)" -ForegroundColor White
Write-Host ""

Write-Host "Opening Stripe Dashboard in your browser..." -ForegroundColor Cyan
Start-Process "https://dashboard.stripe.com/test/apikeys"
Write-Host ""

$publishable_key = Read-Host "Paste your Publishable key (pk_test_...)"
$secret_key = Read-Host "Paste your Secret key (sk_test_...)"

Write-Host ""
Write-Host "STEP 3: Create Products" -ForegroundColor Yellow
Write-Host "  → Go to: https://dashboard.stripe.com/test/products" -ForegroundColor White
Write-Host "  → Click 'Add product'" -ForegroundColor White
Write-Host "  → Create these products:" -ForegroundColor White
Write-Host ""
Write-Host "     Product 1: JARVIS Omega Pro" -ForegroundColor Cyan
Write-Host "       - Monthly: $9/month (recurring)" -ForegroundColor White
Write-Host "       - Yearly: $84/year (recurring)" -ForegroundColor White
Write-Host ""
Write-Host "     Product 2: JARVIS Omega Business" -ForegroundColor Cyan
Write-Host "       - Monthly: $29/month (recurring)" -ForegroundColor White
Write-Host "       - Yearly: $288/year (recurring)" -ForegroundColor White
Write-Host ""

Write-Host "Opening Products page in your browser..." -ForegroundColor Cyan
Start-Process "https://dashboard.stripe.com/test/products"
Write-Host ""

Read-Host "Press Enter after you've created the products"

Write-Host ""
Write-Host "  → Now copy the price IDs from each product" -ForegroundColor White
Write-Host "  → They start with 'price_'" -ForegroundColor White
Write-Host ""

$pro_monthly = Read-Host "Pro Monthly price ID (price_...)"
$pro_yearly = Read-Host "Pro Yearly price ID (price_...)"
$business_monthly = Read-Host "Business Monthly price ID (price_...)"
$business_yearly = Read-Host "Business Yearly price ID (price_...)"

Write-Host ""
Write-Host "STEP 4: Creating .env file..." -ForegroundColor Yellow

# Create .env file
$envContent = @"
# JARVIS OMEGA - Stripe Configuration
# Generated by setup script

# Stripe API Keys
STRIPE_SECRET_KEY=$secret_key
STRIPE_PUBLISHABLE_KEY=$publishable_key

# Stripe Webhook Secret (set this up later)
STRIPE_WEBHOOK_SECRET=whsec_YOUR_WEBHOOK_SECRET_HERE

# Price IDs
PRICE_PRO_MONTHLY=$pro_monthly
PRICE_PRO_YEARLY=$pro_yearly
PRICE_BUSINESS_MONTHLY=$business_monthly
PRICE_BUSINESS_YEARLY=$business_yearly

# Application Settings
DOMAIN=http://localhost:8000
SUPPORT_EMAIL=support@jarvisomega.com

# Flask Settings
FLASK_ENV=development
FLASK_DEBUG=True
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8
Write-Host "[SUCCESS] .env file created!" -ForegroundColor Green

Write-Host ""
Write-Host "STEP 5: Update pricing.html" -ForegroundColor Yellow
Write-Host "  → Open: website\pricing.html" -ForegroundColor White
Write-Host "  → Find line with: const stripe = Stripe('pk_test_...')" -ForegroundColor White
Write-Host "  → Replace with your publishable key: $publishable_key" -ForegroundColor White
Write-Host ""

Write-Host "Opening pricing.html..." -ForegroundColor Cyan
$pricingPath = "..\pricing.html"
if (Test-Path $pricingPath) {
    Start-Process notepad $pricingPath
} else {
    Write-Host "[WARNING] pricing.html not found at expected location" -ForegroundColor Red
}

Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║                    SETUP COMPLETE!                         ║" -ForegroundColor Green
Write-Host "╚════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""

Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Update the Stripe key in website\pricing.html (line ~412)" -ForegroundColor White
Write-Host "  2. Run: .\start-api.ps1" -ForegroundColor White
Write-Host "  3. Open website\pricing.html in your browser" -ForegroundColor White
Write-Host "  4. Test with card: 4242 4242 4242 4242" -ForegroundColor White
Write-Host ""

$response = Read-Host "Do you want to start the API server now? (y/n)"
if ($response -eq 'y') {
    .\start-api.ps1
}
